version: "3.9"
services:
  mongodb:
    image: mongo:7
    container_name: quizarena-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - quiz_mongodb_data:/data/db

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: quizarena-api
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - "4000:4000"
    env_file:
      - apps/api/.env
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongodb:27017/quizarena
      USE_IN_MEMORY_CACHE: "true"

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        VITE_API_URL: http://localhost:4000/api
    env_file:
      - apps/web/.env
    container_name: quizarena-web
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "5173:80"

volumes:
  quiz_mongodb_data:

